#!/bin/bash

sermon_id="$1"

if [ -z "$sermon_id" -o ! -f sermons/${sermon_id}_*.cs.md ]
then
	echo "USAGE: $0 sermon_id"
	echo
	echo "Where sermon_id is the two digit number of the sermon"
	exit -1
fi

sermon_base="$(ls sermons/${sermon_id}_*.cs.md | sed s/.cs.md//g)"

# summarize
echo "cat $sermon_base.cs.md | llm -m openrouter/deepseek/deepseek-chat -s \"\$(cat summary.prompt)\" > $sermon_base.summary.en.md"
time  cat $sermon_base.cs.md | llm -m openrouter/deepseek/deepseek-chat -s "$(cat summary.prompt)" > $sermon_base.summary.en.md

# translate
echo "cat $sermon_base.cs.md | llm -m openrouter/openai/gpt-5.1 -s \"\$(cat translation.prompt)\" > $sermon_base.en_gpt5.1.md"
time  cat $sermon_base.cs.md | llm -m openrouter/openai/gpt-5.1 -s "$(cat translation.prompt)" > $sermon_base.en_gpt5.1.md
