#!/bin/bash

sermon_id="$1"

if [ -z "$sermon_id" -o ! -f sermons/${sermon_id}_*.cs.md ]
then
	echo "USAGE: $0 sermon_id"
	echo
	echo "Where sermon_id is the two digit number of the sermon"
	exit -1
fi

sermon_base="$(ls sermons/${sermon_id}_*.cs.md | sed s/.cs.md//g)"

# summarize
if [ ! -f "$sermon_base.summary.en.md" ]
then
	echo "cat $sermon_base.cs.md | llm -m openrouter/deepseek/deepseek-chat -s \"\$(cat summary.prompt)\" > $sermon_base.summary.en.md"
	time  cat $sermon_base.cs.md | llm -m openrouter/deepseek/deepseek-chat -s "$(cat summary.prompt)" > $sermon_base.summary.en.md
fi

# translate
#if [ ! -f "$sermon_base.en_grok4.md" ]
#then
#	echo "cat $sermon_base.cs.md | llm -m openrouter/x-ai/grok-4 -s \"\$(cat translation.prompt)\" > $sermon_base.en_grok4.md"
#	time  cat $sermon_base.cs.md | llm -m openrouter/x-ai/grok-4 -s "$(cat translation.prompt)" > $sermon_base.en_grok4.md
#fi
#
#if [ ! -f "$sermon_base.en_deepseek-v3.2.md" ]
#then
#	echo "cat $sermon_base.cs.md | llm -m openrouter/deepseek/deepseek-v3.2 -s \"\$(cat translation.prompt)\" > $sermon_base.en_deepseek-v3.2.md"
#	time  cat $sermon_base.cs.md | llm -m openrouter/deepseek/deepseek-v3.2 -s "$(cat translation.prompt)" > $sermon_base.en_deepseek-v3.2.md
#fi
#
#if [ ! -f "$sermon_base.en_opus4.5.md" ]
#then
#	echo "cat $sermon_base.cs.md | llm -m openrouter/anthropic/claude-opus-4.5 -s \"\$(cat translation.prompt)\" > $sermon_base.en_opus4.5.md"
#	time  cat $sermon_base.cs.md | llm -m openrouter/anthropic/claude-opus-4.5 -s "$(cat translation.prompt)" > $sermon_base.en_opus4.5.md
#fi

if [ ! -f "$sermon_base.en_gpt5.1.md" ]
then
	echo "cat $sermon_base.cs.md | llm -m openrouter/openai/gpt-5.1 -s \"\$(cat translation.prompt)\" > $sermon_base.en_gpt5.1.md"
	time  cat $sermon_base.cs.md | llm -m openrouter/openai/gpt-5.1 -s "$(cat translation.prompt)" > $sermon_base.en_gpt5.1.md
fi

exit 

if [ ! -f "$sermon_base.en_gpt5.2.md" ]
then
	echo "cat $sermon_base.cs.md | llm -m openrouter/openai/gpt-5.2 -s \"\$(cat translation.prompt)\" > $sermon_base.en_gpt5.2.md"
	time  cat $sermon_base.cs.md | llm -m openrouter/openai/gpt-5.2 -s "$(cat translation.prompt)" > $sermon_base.en_gpt5.2.md
fi

if [ ! -f "$sermon_base.en_gemini-3-pro.md" ]
then
	echo "cat $sermon_base.cs.md | llm -m openrouter/google/gemini-3-pro-preview -s \"\$(cat translation.prompt)\" > $sermon_base.en_gemini-3-pro.md"
	time  cat $sermon_base.cs.md | llm -m openrouter/google/gemini-3-pro-preview -s "$(cat translation.prompt)" > $sermon_base.en_gemini-3-pro.md
fi
